language: java
jdk:
  - openjdk11
befor_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

service:
  #linking Travis Ci and docker
  - docker
before_install:
  - echo "$DOKCER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jdk-alpine

script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker
  - mvn deploy
